### PR TITLE
Added Materia color scheme (https://github.com/Defman21/base16-materia)

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by auduchinok** [comment]
Merged in https://github.com/auduchinok/base16-builder along with other pull requests.
I'm going to maintain this project for some time, so this pull request can be closed.

**Comment by chriskempson** [comment]
Thanks, would you mind maintaining this in your own repository like https://github.com/chriskempson/base16-default-scheme. The new base16 builders can then pull this scheme from your repository and inherit any updates/tweaks you make in the future.

**Comment by Defman21** [comment]
https://github.com/Defman21/base16-materia

**Comment by chriskempson** [comment]
Thanks for the link. Any chance you could rename the yml file to yaml? Also don't forget to add yourself here: https://github.com/chriskempson/base16/blob/master/README.md#scheme-repositories 😄

**Comment by Defman21** [comment]
Okay!

**Pull request closed without merging**
