### PR TITLE
Fix https://github.com/chriskempson/base16-builder/issues/311

### PR DESCRIPTION
**Pull request by kowalskey**

### CODE REVIEW

**Comment by cmcginty** [comment]
I just hit the same bug. Can you merge this pull request?

**Comment by korzhyk** [comment]
OMG! Merge this PR.

**Comment by pathawks** [comment]
Duplicate of #306

**Comment by auduchinok** [comment]
Merged in https://github.com/auduchinok/base16-builder along with other pull requests.
I'm going to maintain this project for some time, so this pull request can be closed.

**Pull request merged**
