### PR TITLE
Non base16 schemes

### PR DESCRIPTION
**Pull request by ohspite**
base16-builder is a great tool for specifying a color theme one time, and then generating config files for multiple applications.  Right now it really only supports base16 style themes, but it could be a tool that can be used to generate any color theme for any terminal or application from a single specification.  That would make it **the tool** for generating terminal color themes.

This pull request expands the allowed fields in the scheme files so that other, less-civilized 16-color terminal themes can be generated as well.  Instead of "base00", "base01", etc. they use the fields "color0", "color1", etc, as well as "foreground" and "background".  

For example, there are tons of schemes here: https://github.com/mbadolato/iTerm2-Color-Schemes.  They can be converted to the base16 YAML format once, and then they will work in any of the application templates.  They won't have the nice base16 properties, especially for vi or emacs, but for terminal emulators they function exactly as intended.

(Incidentally, I already did the conversion of those iterm2 themes and tested them in guake and gnome-terminal.  But there are 100+ themes so I didn't add them all to the pull request.)

These commits also allow optionally specifying alternate "bright" colors for bold characters in base16 themes, as well as foreground and background colors.  But if you don't specify them, everything functions exactly as it currently does.  The alternate bold colors are defined by using fields such as "base0808" and "base0A0A", and can be defined for colors 08, 0A, 0B, 0C, 0D, and 0E.  

Not all templates have been updated to take advantage of these changes yet; only the gnome-terminal, shell, and guake templates are updated in these commits.

The second commit adds a modified gnome-terminal template that allows a profile to be dynamically updated, so it can be used similar to the shell or guake templates.  This is definitely a different feature, but since the template handles option foreground/background/bold colors, it depends on the first commit.

### CODE REVIEW

**Comment by xHN35RQ** [comment]
:+1: I'd love to see this integrated into the main repo... or perhaps put into it's own project. this is good work!

**Comment by aloisdg** [comment]
We could create a sub folder with all *non official* creation. But I am for keeping the 16 colors model for now. We could think about a base16 2.0 with breaking changes. A bit of semver would be nice.

**Comment by ohspite** [comment]
I guess I should mention that this doesn't change the output for any currently existing color themes, and it's backwards compatible with templates that haven't been updated.  The commits just add support to the builder script and a few of the templates for any new color themes that choose to use the expanded options.

We really need @chriskempson to weigh in on this.  I've been thinking about moving this stuff to a different project, but the new functionality is so intertwined with the currently existing templates that it's hard to cleanly separate.  It would be more of a fork than a separate project, and I'd really rather just add it here if Chris is interested.

**Comment by aloisdg** [comment]
@ohspite there are a lot of open PR. A big fork would be a good idea if @chriskempson doesn't have the time (or else) to manage the project. I would love to see an organization with a fork of base16 and one of base16-builder.

**Comment by ohspite** [comment]
The number of PRs is a good point, @aloisdg.  I'll add it to my todo list.  If Chris or you or somebody else hasn't gotten around to it by the time that I have time, I'll definitely look into it.

**Pull request closed without merging**
